version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: checkmyvehicle_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: checkmyvehicle
    ports:
      - '3306:3306'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: checkmyvehicle_backend
    restart: unless-stopped
    ports:
      - '5000:5000'
    env_file:
      - ./backend/.env
    depends_on: # <-- ESTO ES CLAVE PARA LA COMUNICACIÓN INTERNA
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: checkmyvehicle_frontend
    restart: unless-stopped
    ports:
      - '3000:80'
    depends_on:
      - backend

volumes:
  db_data: