# Stage 1: Install dependencies
FROM node:18-alpine AS deps
WORKDIR /app
COPY package.json ./
RUN npm install

# Stage 2: Build the application
FROM node:18-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Stage 3: Run the application
FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app ./

EXPOSE 5000
CMD ["npm", "start"]